spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bicycle
    username: bicycleuser
    password: bicyclepass
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl